# Generated by Django 5.0.2 on 2024-05-27 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='carrera',
            field=models.CharField(choices=[('Sistemas Computacionales', 'ISC'), ('Informática', 'II'), ('TICS', 'ITICS'), ('Industrial', 'II')], max_length=50),
        ),
    ]
