# Generated by Django 5.0.2 on 2024-05-28 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_customuser_carrera'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='año_publicacion',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='semestre',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='titulo',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='carrera',
            field=models.CharField(choices=[('Sistemas Computacionales', 'ISC'), ('Informática', 'II'), ('TICS', 'ITICS'), ('Industrial', 'II')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='nivel_educativo',
            field=models.CharField(choices=[('LIC', 'Licenciatura/Ingeniería'), ('POS', 'Posgrado')], max_length=5, null=True),
        ),
    ]
