# Generated by Django 5.1.5 on 2025-02-08 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_customuser_año_publicacion_customuser_semestre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='año_publicacion',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='titulo',
        ),
    ]
